# -*- coding: utf-8 -*-
"""Cleaned_sales_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0y2X_uVkHjYfTpeIB_cpOp8KHhZ5nD2
"""

import pandas as pd
import numpy as np

# Load dataset (update path to your file)
df = pd.read_csv('Sample - Superstore.csv', encoding='latin1')

# Inspect data
print("Initial Data Info:")
print(df.info())
print("\nFirst 5 Rows:")
print(df.head())

# Handle missing values
df.fillna({'Sales': 0, 'Profit': 0, 'Quantity': 0}, inplace=True)

# Convert date columns to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Remove duplicates
df.drop_duplicates(inplace=True)

# Create calculated field: Profit Margin (%)
df['Profit Margin'] = (df['Profit'] / df['Sales']) * 100
df['Profit Margin'] = df['Profit Margin'].replace([np.inf, -np.inf], 0)  # Handle division by zero

# Extract year and month
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.to_period('M')

# Save cleaned data
df.to_csv('cleaned_superstore_data.csv', index=False)
print("\nCleaned data saved to 'cleaned_superstore_data.csv'")